export const LOAD_PRODUCT_REQUEST = 'LOAD_PRODUCT_REQUEST';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_TOP_REQUEST = 'LOAD_PRODUCTS_TOP_REQUEST';
export const LOAD_PRODUCTS_TOP_SUCCESS = 'LOAD_PRODUCTS_TOP_SUCCESS';
export const RESET_PRODUCT_CUSTOMERS = 'RESET_PRODUCT_CUSTOMERS';
export const LOAD_PRODUCT_CUSTOMERS_REQUEST = 'LOAD_PRODUCT_CUSTOMERS_REQUEST';
export const LOAD_PRODUCT_CUSTOMERS_SUCCESS = 'LOAD_PRODUCT_CUSTOMERS_SUCCESS';

export const LOAD_ORDER_REQUEST = 'LOAD_ORDER_REQUEST';
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS';
export const LOAD_ORDERS_REQUEST = 'LOAD_ORDERS_REQUEST';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';

export const LOAD_CUSTOMER_REQUEST = 'LOAD_CUSTOMER_REQUEST';
export const LOAD_CUSTOMER_SUCCESS = 'LOAD_CUSTOMER_SUCCESS';
export const LOAD_CUSTOMERS_REQUEST = 'LOAD_CUSTOMERS_REQUEST';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';

export const LOAD_STATS_REQUEST = 'LOAD_STATS_REQUEST';
export const LOAD_STATS_SUCCESS = 'LOAD_STATS_SUCCESS';
